name: Test

on:
    push:
        branches:
            - master
            - release/*
    pull_request:
        branches:
            - master
            - release/*

jobs:
    run:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['7.0', '7.1', '7.2', '7.3', '7.4']
        name: PHP ${{ matrix.php }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            # https://github.com/shivammathur/setup-php
            -   name: Setup
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: xdebug

            -   id: composer-cache-dir
                run: echo "::set-output name=dir::$(composer config cache-dir)"

            -   uses: actions/cache@v2
                id: composer-cache
                with:
                    path: ${{ steps.composer-cache-dir.outputs.dir }}
                    key: composer-${{ runner.OS }}-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
                    restore-keys: |
                        composer-${{ runner.OS }}-${{ hashFiles('composer.json') }}-
                        composer-${{ runner.OS }}-
                        composer-

            -   name: Validate
                run: composer validate --strict

            -   name: Set GitHub token
                run: composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}

            -   name: Set Composer packagist token               
                run: composer config --global --auth http-basic.repo.packagist.com token ${{ secrets.COMPOSER_PACKAGIST_COM_TOKEN }}

            -   name: Install
                run: composer install --prefer-dist --no-progress

            -   name: Test
                run: composer run-script test
